"""init

Revision ID: 1f39ff03158f
Revises: 
Create Date: 2026-04-27 21:38:30.410229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f39ff03158f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('hardware_id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_index(op.f('ix_stations_hardware_id'), 'stations', ['hardware_id'], unique=True)
    op.create_index(op.f('ix_stations_org_id'), 'stations', ['org_id'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['stations.field_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_date_time'), 'sensor_data', ['date_time'], unique=False)
    op.create_index(op.f('ix_sensor_data_field_id'), 'sensor_data', ['field_id'], unique=False)
    op.create_table('station_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['stations.field_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_data_date_time'), 'station_data', ['date_time'], unique=False)
    op.create_index(op.f('ix_station_data_field_id'), 'station_data', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_data_field_id'), table_name='station_data')
    op.drop_index(op.f('ix_station_data_date_time'), table_name='station_data')
    op.drop_table('station_data')
    op.drop_index(op.f('ix_sensor_data_field_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_date_time'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_stations_org_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_hardware_id'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
