"""add station polling interval

Revision ID: ad7ff15ca17e
Revises: 1f39ff03158f
Create Date: 2026-05-29 13:43:22.683716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7ff15ca17e'
down_revision: Union[str, None] = '1f39ff03158f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('polling_interval_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'polling_interval_seconds')
    # ### end Alembic commands ###
